#!/bin/bash

#########################################
# Squid Proxy Installer (SPI)           #
# Version: 2.0 Build 2001               #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Author: Hidden Refuge (© 2014 - 2015) #
# License: MIT License                  #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Project Page: https://tny.im/3kW      #
#########################################

# Main function
main()	{
	# Declaring a few misc variables
	vspiversion=2.0 # SPI version
	vspibuild=2001 # SPI build number
	vsysarch=$(getconf LONG_BIT) # System architecture
	voption=$1 # Parameter for given options
	
	# Checking $voption and running corresponding function
	case $voption in
	'-rhel5') # If option "-rhel5" run function rhel5
		rhel5;; # RHEL 5 Linux distributions such as Red Hat 5, CentOS 5 and et cetera
	'-rhel6') # If option "-rhel6" run function rhel6
		rhel6;; # RHEL 6 Linux distributions such as Red Hat 6, CentOS 6 and et cetera
	'-rhel7') # If option "-rhel7" run function rhel7
		rhel7;;	# RHEL 7 Linux distributions such as Red Hat 7, CentOS 7 and et cetera
	'-debian') # If option "-debian" run fuction deb
		deb;; # Debian "Squeeze" 6 and Debian "Wheezy" 7
	'-jessie') # If option "-jessie" run function deb8
		deb8;; # Debian "Jessie" 8
	'-ubuntu') # If option "-ubuntu" run function ubt
		ubt;; # Ubuntu
	'-fedora') # If option "fedora" run function fed
		fed;; # Fedora 
	*) # If option empty or non existing run function info
		info;; # Default, information about available options and et cetera
	esac
}

# Function for RHEL 5 Linux distributions
rhel5()	{
	rpm -Uvh http://flexbox.sourceforge.net/centos/5/i386/flexbox-release-1-4.3.noarch.rpm
	yum install perl-DBI libecap squid httpd -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid/passwd $usrn
	case $arch in
			32)
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5632.conf --no-check-certificate;;
			64)
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5664.conf --no-check-certificate;;
	esac
	service squid restart && chkconfig squid on
	service httpd stop && chkconfig httpd off
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	service iptables save
	touch /etc/squid/blacklist.acl
}
rhel6 () {
	yum install squid httpd-tools -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid/passwd $usrn
	case $arch in
			32)
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5632.conf --no-check-certificate;;
			64)
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5664.conf --no-check-certificate;;
	esac
	service squid restart && chkconfig squid on
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	service iptables save
	touch /etc/squid/blacklist.acl
}
rhel7 () {
	yum install squid httpd-tools -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid/passwd $usrn
	wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel7.conf --no-check-certificate
	systemctl restart squid.service && systemctl enable squid.service
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	iptables-save
	touch /etc/squid/blacklist.acl
}
deb ()	{
	apt-get update
	apt-get install apache2-utils squid3 -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid3/passwd $usrn
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-debian.conf --no-check-certificate
	service squid3 restart && update-rc.d squid3 defaults
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	iptables-save
	touch /etc/squid3/blacklist.acl
}
deb8 () {
	apt-get update
	apt-get install apache2-utils squid3 -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid3/passwd $usrn
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-jessie.conf --no-check-certificate
	service squid3 restart && update-rc.d squid3 defaults
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	iptables-save
	touch /etc/squid3/blacklist.acl
}
ubt ()	{
	apt-get update
	apt-get install apache2-utils squid3 -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid3/passwd $usrn
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-ubuntu.conf --no-check-certificate
	cp /etc/init/squid3.conf /etc/init.d/squid3
	service squid3 restart && update-rc.d squid3 defaults
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	iptables-save
	touch /etc/squid3/blacklist.acl
}
fed() {
	yum install squid httpd-tools -y
	read -e -p "Your desired username: " usrn
	htpasswd -c /etc/squid/passwd $usrn
	case $arch in
		32)
			wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-fedora32.conf --no-check-certificate;;
		64)
			wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel7.conf --no-check-certificate;;
	esac
	systemctl restart squid && systemctl enable squid
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Workaround for some iptables setups
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
	iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
	iptables-save
	touch /etc/squid/blacklist.acl
}
info ()	{
	echo "Squid Proxy Installer $vspiversion $vspibuild"
	echo ""
	echo "Usage: ./spi <option>"
	echo "Example for Debian 6/7: ./spi -debian"
	echo ""
	echo "Options:"
	echo "-rhel5   <<-- RHEL 5 based OS 32/64 Bit"
	echo "-rhel6   <<-- RHEL 6 based OS 32/64 Bit"
	echo "-rhel7   <<-- RHEL 7 based OS 32/64 Bit"
	echo "-debian  <<-- Debian 6,7 32/64 Bit"
	echo "-jessie  <<-- Debian 8 32/64 Bit"
	echo "-ubuntu  <<-- Ubuntu 32/64 Bit"
	echo "-fedora  <<-- Fedora 32/64 Bit"
	echo ""
	echo "RHEL 5: CentOS 5, Scientific Linux 5, etc.."
	echo "RHEL 6: CentOS 6, Scientific Linux 6, etc.."
	echo "RHEL 7: CentOS 7, Scientific Linux 7, etc.."
	echo ""
	echo "To add more users use the command below:"
	echo "Debian/Ubuntu: htpasswd /etc/squid3/passwd username"
	echo "RHEL/Fedora: htpasswd /etc/squid/passwd username"
	echo ""
}

main
