#!/bin/bash

#########################################
# Squid Proxy Installer (SPI)           #
# Version: 2.0 Build 2004               #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Author: Hidden Refuge (© 2014 - 2015) #
# License: MIT License                  #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Project Page: https://tny.im/3kW      #
#########################################

# Main function
main()	{
	# Declaring a few misc variables
	vspiversion=2.0 # SPI version
	vspibuild=2004 # SPI build number
	vsysarch=$(getconf LONG_BIT) # System architecture
	voption=$1 # Parameter for given options
	
	# Checking $voption and running corresponding function
	case $voption in
	'-rhel5') # If option "-rhel5" run function rhel5
		rhel5;; # RHEL 5 Linux distributions such as Red Hat 5, CentOS 5 and et cetera
	'-rhel6') # If option "-rhel6" run function rhel6
		rhel6;; # RHEL 6 Linux distributions such as Red Hat 6, CentOS 6 and et cetera
	'-rhel7') # If option "-rhel7" run function rhel7
		rhel7;;	# RHEL 7 Linux distributions such as Red Hat 7, CentOS 7 and et cetera
	'-debian') # If option "-debian" run fuction deb
		deb;; # Debian "Squeeze" 6 and Debian "Wheezy" 7
	'-jessie') # If option "-jessie" run function deb8
		deb8;; # Debian "Jessie" 8
	'-ubuntu') # If option "-ubuntu" run function ubt
		ubt;; # Ubuntu
	'-fedora') # If option "fedora" run function fed
		fed;; # Fedora 
	*) # If option empty or non existing run function info
		info;; # Default, information about available options and et cetera
	esac
}

# Function for iptables rules (CentOS 5 & 6)
firew1()	{
	# Opening default Squid port 3128 for clients to connect
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Saving firewall rules
	service iptables save
}

# Function for iptables rules (CentOS 7, Debian, Ubuntu, Fedora)
firew2()	{
	# Opening default Squid port 3128 for clients to connect
	iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
	# Saving firewall rules
	iptables-save
}

# Function for RHEL 5 Linux distributions
rhel5()	{
	# Downloading and installing necessary repo for newer Squid 3 versions for CentOS 5
	rpm -Uvh http://flexbox.sourceforge.net/centos/5/i386/flexbox-release-1-4.3.noarch.rpm
	# Installing necessary packages (Squid, httpd for htpasswd and dependencies)
	yum install perl-DBI libecap squid httpd -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid/passwd $usrn
	# Downloading necessary Squid.conf for the corresponding OS & system architecture
	case $vsysarch in
			32) # 32 bit Squid configuration
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5632.conf --no-check-certificate;;
			64) # 64 bit Squid configuration
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5664.conf --no-check-certificate;;
	esac
	# Restarting Squid and enabling its service
	service squid restart && chkconfig squid on
	# Turning off httpd and removing it from services (post installation of yum enabled it but we don't need it)
	service httpd stop && chkconfig httpd off
	# Running function firew1
	firew1
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid/blacklist.acl
}

# Function for RHEL 6 Linux distributions
rhel6 () {
	# Installing necessary packages (Squid, httpd-tools for htpasswd and dependencies)
	yum install squid httpd-tools -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid/passwd $usrn
	# Downloading necessary Squid.conf for the corresponding OS & system architecture
	case $vsysarch in
			32) # 32 bit Squid configuration
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5632.conf --no-check-certificate;;
			64) # 64 bit Squid configuration
					wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel5664.conf --no-check-certificate;;
	esac
	# Restarting Squid and enabling its service
	service squid restart && chkconfig squid on
	# Running function firew1
	firew1	
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid/blacklist.acl
}

# Function for RHEL 7 Linux distributions
rhel7 () {
	# Installing necessary packages (Squid, httpd-tools for htpasswd and dependencies)
	yum install squid httpd-tools -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid/passwd $usrn
	# Downloading Squid configuration 
	wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel7.conf --no-check-certificate
	# Restarting Squid and enabling its service
	systemctl restart squid.service && systemctl enable squid.service
	# Running function firew2
	firew2
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid/blacklist.acl
}

# Function for Debian "Squeeze" 6 and Debian "Wheezy" 7
deb()	{
	# Updating package database
	apt-get update
	# Installing necessary packages (Squid, apache2-utils for htpassword and dependencies)
	apt-get install apache2-utils squid3 -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid3/passwd $usrn
	# Downloading Squid configuration
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-debian.conf --no-check-certificate
	# Restarting Squid and enabling its service
	service squid3 restart && update-rc.d squid3 defaults
	# Running function firew2
	firew2
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid3/blacklist.acl
}

# Function for Debian "Jessie" 8
deb8()	{
	# Updating package database
	apt-get update
	# Installing necessary packages (Squid, apache2-utils for htpassword and dependencies)
	apt-get install apache2-utils squid3 -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid3/passwd $usrn
	# Downloading Squid configuration
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-jessie.conf --no-check-certificate
	# Restarting Squid and enabling its service
	service squid3 restart && update-rc.d squid3 defaults
	# Running function firew2
	firew2
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid3/blacklist.acl
}

# Function for Ubuntu
ubt()	{
	# Updating package database
	apt-get update
	# Installing necessary packages (Squid, apache2-utils for htpassword and dependencies)
	apt-get install apache2-utils squid3 -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid3/passwd $usrn
	# Downloading Squid configuration
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-ubuntu.conf --no-check-certificate
	# Copying squid3.conf from init to init.d for startup script
	cp /etc/init/squid3.conf /etc/init.d/squid3
	# Restarting Squid and enabling its service
	service squid3 restart && update-rc.d squid3 defaults
	# Running function firew2
	firew2
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid3/blacklist.acl
}

# Function for Fedora
fed() {
	# Installing necessary packages (Squid, httpd-tools for htpasswd and dependencies)
	yum install squid httpd-tools -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid/passwd $usrn
	# Downloading necessary Squid.conf for the corresponding OS & system architecture
	case $vsysarch in
		32) # 32 bit Squid configuration
			wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-fedora32.conf --no-check-certificate;;
		64) # 64 bit Squid configuration
			wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-rhel7.conf --no-check-certificate;;
	esac
	# Restarting Squid and enabling its service
	systemctl restart squid && systemctl enable squid
	# Running function firew2
	firew2
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid/blacklist.acl
}

# Default function with information
info()	{
	echo "Squid Proxy Installer $vspiversion Build $vspibuild"
	echo ""
	echo "Usage: ./spi <option>"
	echo "Example (Debian 6/7): ./spi -debian"
	echo ""
	echo "Options:"
	echo "-rhel5   <<-- RHEL 5 based OS 32/64 Bit"
	echo "-rhel6   <<-- RHEL 6 based OS 32/64 Bit"
	echo "-rhel7   <<-- RHEL 7 based OS 32/64 Bit"
	echo "-debian  <<-- Debian 6,7 32/64 Bit"
	echo "-jessie  <<-- Debian 8 32/64 Bit"
	echo "-ubuntu  <<-- Ubuntu 32/64 Bit"
	echo "-fedora  <<-- Fedora 32/64 Bit"
	echo ""
	echo "RHEL 5: CentOS 5, Scientific Linux 5, etc.."
	echo "RHEL 6: CentOS 6, Scientific Linux 6, etc.."
	echo "RHEL 7: CentOS 7, Scientific Linux 7, etc.."
	echo ""
	echo "To add more users use the command below:"
	echo "Debian/Ubuntu: htpasswd /etc/squid3/passwd username"
	echo "RHEL/Fedora: htpasswd /etc/squid/passwd username"
	echo ""
}

main
